_target_: torchrecipes.audio.source_separation.train_app.SourceSeparationTrainApp

defaults:
  - _self_
  # datamodule
  - schema/datamodule: librimix_datamodule_conf
  - datamodule: librimix
  # trainer
  - schema/trainer: trainer
  - trainer: gpu
