train:
  _target_: torchvision.datasets.FakeData
  transform:
    _target_: torchvision.transforms.ToTensor
val:
  _target_: torchvision.datasets.FakeData
  transform:
    _target_: torchvision.transforms.ToTensor
test:
  _target_: torchvision.datasets.FakeData
  transform:
    _target_: torchvision.transforms.ToTensor
