# Black + usort
[[linter]]
code = 'UFMT'
include_patterns = [
    '**/*.py',
]
command = [
    'python3',
    'tools/linter/ufmt_linter.py',
    '--',
    '@{{PATHSFILE}}'
]
init_command = [
    'python3',
    'tools/linter/pip_init.py',
    '--dry-run={{DRYRUN}}',
    'black==22.3.0',
    'ufmt==1.3.3',
    'usort==1.0.2',
]
is_formatter = true
